# Generated by Django 5.1.4 on 2025-01-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comments_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='isDraft',
            field=models.BooleanField(default=False),
        ),
    ]
