# Generated by Django 5.1.4 on 2025-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_isdraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(to='blogs.tags'),
        ),
    ]
